# Generated by Django 3.2 on 2022-09-03 14:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='logo/')),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('addressLocality', models.CharField(blank=True, max_length=100)),
                ('addressRegion', models.CharField(blank=True, max_length=100)),
                ('postalCode', models.CharField(blank=True, max_length=100)),
                ('addressCountry', models.CharField(blank=True, max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=100)),
                ('longitude', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='favicon/')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('owner_facebook', models.CharField(blank=True, max_length=150)),
                ('owner_instagram', models.CharField(blank=True, max_length=150)),
                ('owner_twiter', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
