# Generated by Django 3.2 on 2022-09-03 14:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_site_profile_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_profile',
            name='icon',
        ),
        migrations.AddField(
            model_name='site_profile',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='favicon'),
        ),
    ]
