# Generated by Django 3.2 on 2022-09-06 12:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220903_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(max_length=20)),
                ('title_bold', models.CharField(max_length=20)),
                ('title_normal', models.CharField(max_length=10)),
                ('decs', models.CharField(max_length=180)),
                ('link', models.CharField(max_length=180)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
