# Generated by Django 3.2 on 2022-09-09 14:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('sub_title', models.CharField(max_length=20)),
                ('title_bold', models.CharField(max_length=20)),
                ('link_text', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=180)),
            ],
        ),
    ]
