# Generated by Django 3.0.7 on 2022-11-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_coustomer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_profile',
            name='pixels',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
