# Generated by Django 3.0.7 on 2022-11-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_site_profile_pixels'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='site_profile',
            name='email',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='site_profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='site_profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
