# Generated by Django 3.0.7 on 2022-12-17 06:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20221103_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='link',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='decs',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_bold',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_bold',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_normal',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='top_title',
        ),
        migrations.AddField(
            model_name='banner',
            name='fisimage',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='fis-image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='secimage',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='sec-image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='mobimage',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='mob-image'),
            preserve_default=False,
        ),
    ]
