# Generated by Django 3.0.7 on 2022-12-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20221217_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coustomer_image_slider',
        ),
        migrations.DeleteModel(
            name='Coustomer_text',
        ),
    ]
