# Generated by Django 3.0.7 on 2022-12-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20221217_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Side_Nav',
        ),
    ]
