# Generated by Django 3.0.7 on 2022-12-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_side_nav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foot2_Nav',
        ),
        migrations.DeleteModel(
            name='Foot3_Nav',
        ),
    ]
