# Generated by Django 3.0.7 on 2022-12-18 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20221217_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_profile',
            name='whitelogo',
        ),
    ]
