# Generated by Django 3.0.7 on 2022-12-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_site_profile_whitelogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_profile',
            name='youtube',
        ),
    ]
