# Generated by Django 3.0.7 on 2022-12-18 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_site_profile_fax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='site_profile',
            name='longitude',
        ),
    ]
