# Generated by Django 3.0.7 on 2022-11-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
    ]
