# Generated by Django 3.0.7 on 2022-11-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=1, editable=False, max_length=5),
            preserve_default=False,
        ),
    ]
