# Generated by Django 3.0.7 on 2022-11-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='user',
        ),
    ]
