# Generated by Django 3.0.7 on 2022-12-17 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20221102_1537'),
        ('order', '0009_remove_orderproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Variants'),
            preserve_default=False,
        ),
    ]
