# Generated by Django 3.2 on 2022-09-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='agegroup',
            field=models.IntegerField(blank=True, default=1, max_length=2),
            preserve_default=False,
        ),
    ]
