# Generated by Django 3.2 on 2022-09-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_agegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='agegroup',
            field=models.IntegerField(blank=True),
        ),
    ]
