# Generated by Django 3.0.7 on 2022-11-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20221102_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Material',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Weight',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
