# Generated by Django 3.0.7 on 2022-12-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_blogmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='agegroup',
        ),
    ]
