# Generated by Django 3.0.7 on 2022-12-17 14:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20221217_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='size_image',
            field=cloudinary.models.CloudinaryField(default=0, max_length=255, verbose_name='size image'),
            preserve_default=False,
        ),
    ]
