# Generated by Django 3.0.7 on 2022-12-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_amazon_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='amazon_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
