# Generated by Django 3.0.7 on 2022-12-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_variants_amazon_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_image',
        ),
        migrations.AddField(
            model_name='product',
            name='mpn',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
